"""Add domains table

Revision ID: 43b883c483b4
Revises: 503ccf09b8b3
Create Date: 2021-12-22 02:17:27.001953

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '43b883c483b4'
down_revision = '503ccf09b8b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domains')
    # ### end Alembic commands ###
