"""Add totp

Revision ID: 503ccf09b8b3
Revises: d37e59e7e139
Create Date: 2021-12-19 16:33:49.853314

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '503ccf09b8b3'
down_revision = 'd37e59e7e139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp')
    # ### end Alembic commands ###
