version: "3.6"

services:
  api:
    build: ./api
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/api
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
  caddy:
    image: caddy:2-alpine
    command: caddy run
    working_dir: /etc/caddy
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - api

volumes:
  caddy_data: {}
  caddy_config: {}
